theme: jekyll-theme-minimal
title: Battesimo di Elena
description: 7 dicembre 2025 ore 11 Chiesa di San Raimondo Nonnato, Roma (<a href="https://maps.app.goo.gl/w43DzhpSeExghGmx5">qui</a>)
logo: /assets/img/invito_elena.png
